version: "3.2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=coon
      - POSTGRES_USER=coon
      - POSTGRES_DB=coon_packages
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  influxdb:
    build:
      context: ./docker/
      dockerfile: Dockerfile-influxdb
    environment:
      - INFLUXDB_DB=collectd
      - INFLUXDB_READ_USER=metrics
      - INFLUXDB_READ_USER_PASSWORD=password
    volumes:
      - "./docker/influxdb.conf:/etc/influxdb/influxdb.conf"
    ports:
      - "8086:8086"
      - "25826:25826"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./docker/run_grafana.sh:/run_grafana.sh"
    entrypoint: /run_grafana.sh
    depends_on:
      - influxdb
  builder:
    image: comtihon/coon_auto_builder
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - EMAIL_USER=foo
      - EMAIL_PASSWORD=bar
    volumes:
      - ./builder-data:/coon/artifacts
  collectd:
    build:
      context: ./docker/
      dockerfile: Dockerfile-collectd
    tty: true
    depends_on:
      - influxdb
      - builder